### ISSUE TITLE
Add bower support

### ISSUE THREAD

**Issue by kwn** [tavicu/bs-confirmation#11]
Hello @tavicu 

Could you provide a bower support for this plugin? It's really simple and it should take no more than 15 minutes.

Here's the guide:
http://bower.io/docs/creating-packages/

**Comment by qooob** [comment]
Never dealt with that. What is it for?

**Comment by tavicu** [comment]
Hey!

I will look into it but in the future. Unfortunately right now i'm very busy at work and don't have time.

**Comment by alexdresko** [comment]
I submitted a pull request that does, I think, 90% of what you need to do (https://github.com/tavicu/bootstrap-confirmation/pull/13). 

#13

**Comment by tavicu** [comment]
Hey! Thank you for your help. I added the package to bower.
