### ISSUE TITLE
The library breaks the normal behaviour for a <a> link without confirmation enabled

### ISSUE THREAD

**Issue by tristanbes** [tavicu/bs-confirmation#14]
Hi,

Given this following DOM: 
```html
<a href="/admin.php/8/faq/1/plan/list class="btn btn-default btn-cons btn-notification-style m-b-10 text-success"">faq.manage.plan</a>
```

When using this follwoing JS code:

```js
$(document).ready(function () {
    $('body').confirmation({
        selector: '[data-toggle="confirmation"]',
        btnOkLabel: (typeof confirmationBtnOkLabel !== 'undefined') ? confirmationBtnOkLabel : "interface.delete",
        btnCancelLabel: (typeof confirmationBtnCancelLabel !== 'undefined') ? confirmationBtnCancelLabel : "interface.cancel",
        onConfirm: function(event, element) {
            window.location.href = element.attr('href');
        }
    });
```

It results in the impossibility to click on the link or any other link. We click, and nothing happens, as if the redirection was prohibed by the plugin. (Once again, it shouldn't interefeer since the link doesn't have the proper selector)

Removing the JS code and the `a` link is working again.

Using jquery 1.11

**Comment by tavicu** [comment]
Hi.

Check your commas in html code.

**Comment by jancinert** [comment]
tristanbes:
see https://github.com/tavicu/bs-confirmation/issues/16#issuecomment-148966244
