### ISSUE TITLE
Question about usage of selector

### ISSUE THREAD

**Issue by rhelms** [tavicu/bs-confirmation#16]
I was wondering about the usage of the selector option, and when it is appropriate to use it.

I had some code looking like the following:

        jQuery('body').confirmation({
            selector: '.delete-business-connection-action[data-toggle="confirmation"]',
            container: '.legallink-bootstrap',
            onConfirm: function (event, element) {
                deleteBusinessConnection(jQuery(element).data('business-connection-id'));
            }
        });

The intention was that I would load the confirmation functionality against the `body`, but it would use the selector to attach to any elements that existed at the time.

However, it seemed that because I had initialised against the body element, this bit of code from the lib would kick in and prevent any buttons from the clicked or checkboxes from being selected.

        $(element).on('click', function(e) {
			e.preventDefault();
		});

I've since moved the contents of the selector option into my actual jQuery selector, but it does seem to reduce the usefulness of it.

I supposed somewhere in the back of my mind, it might enable delegation of events. i.e.

    jQuery('body').on('click', selector, function(){ /* do confirmation stuff */});

but I guess I might still me missing the initialisation, should any content be loaded via Ajax.

**Comment by behiunforgiven** [comment]
Did you solve the problem?

**Comment by tavicu** [comment]
The preventDefault on click its bind after the plugin is initialized so no problem there. All it does is to remove the action from the link.

If something it's not working on your script means that you are doing something wrong and not logical. Most probably in your code you put stoppropagation too that stops other click functions.

**Comment by jancinert** [comment]
tavicu:

Unfortunately You did not understand the problem.
If someone uses the 'selector' option then the main jQuery element is not the one that should trigger a confirmation. The main jQuery element is some ancestor node.

The already mentioned code snippet below will prevent ANY link inside passed ancestor node (eg. table, body, div) to be navigated.
```
    $(element).on('click', function(e) {
        e.preventDefault();
    });
```

**Comment by tavicu** [comment]
@jancinert I did the changes on the plugin. Thanks.
