### ISSUE TITLE
work with 'append' operation

### ISSUE THREAD

**Issue by fangfangbest** [tavicu/bs-confirmation#18]
when dynamic appends a confirmation button, how to support it

**Comment by tavicu** [comment]
Hey, use selector.

$('body').confirmation({
	selector: '[data-toggle="confirmation"]'
});

**Comment by fangfangbest** [comment]
good! but im still wandering that how can i get a [data-toggle] button's id in the confirmation function

**Comment by tavicu** [comment]
I don't understand what id do you want to get. On confirm function is like this function(event, element){}

So you have the event and the element and you can use in the function

**Comment by jancinert** [comment]
fangfangbest:

Currently it is not possible.
`options.onConfirm(event, that.$element)`
that.$element is not the element that was clicked

**Comment by amigaser** [comment]
function(event, element){
   console.log(element[0].id);
}
