### ISSUE TITLE
href callback not working properly

### ISSUE THREAD

**Issue by Pirozek** [tavicu/bs-confirmation#22]
Hi, there is a bug when calling ```href``` callback instead of using ```'data-href'``` attribute. Problem is with the way of calling those callback. Here, let me demonstrate:

```javascript
return $e.attr('data-href') || (typeof o.href == 'function' ? o.href.call($e[0]) : o.href);
````

When you look into call function documentation (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/call) you will discover, that first parameter to call needs to be scope (```thisArg```), so right way to use ```call``` in this case is:

```javascript
o.href.call(this, $e[0])
```
Or simply:
```javascript
o.href($e[0])
```

This problem is with every ```.call``` in your library, should I fix it for you with pull request, or will you repair it by yourself? :)

**Comment by tavicu** [comment]
Hey.

Thanks for your help.

I will fix it.
