### ISSUE TITLE
Scrolls to the top

### ISSUE THREAD

**Issue by un33k** [tavicu/bs-confirmation#23]
Ideally, you would want to click, let's say `delete` to remove an `li` in its spot. Unfortunately, as soon as the `delete` is clicked, the page jumps to the top.

Is the a bug, mis-configuration or a feature I can turn off. Just looking for a way to disable the move.

**Comment by tavicu** [comment]
You need to call event.preventDefault(); on "onConfirm" method.

**Comment by un33k** [comment]
Great. thx
