### ISSUE TITLE
getting TypeError: Cannot set property 'click' of undefined

### ISSUE THREAD

**Issue by jacobEwing** [tavicu/bs-confirmation#25]
This seems to work nicely, but (using Chrome v45.0.something), I'm getting the error in the developer tools:

Uncaught TypeError: Cannot set property 'click' of undefined

That's this line, 141:

```
            that.inState.click = false;
```

And indeed, when I look the 'that' object, there is no inState value.

I added this at the top of the "Confirmation" definition:

```
            if(this.inState == undefined) this.inState = {};
```

And that seems to have fixed it.  Not sure where else that would be defined.

**Comment by dovy** [comment]
+1  Error no more.

**Comment by walkerdepaula** [comment]
I "fixed this" by updating my bootstrap and jquery

**Comment by bastarder** [comment]
my bootstrap is 3.XXX  why i have this problem too? is there any solution?

**Comment by opure** [comment]
I can also have this problem,the bootstrap.js version is greater than 3.3.

**Comment by tavicu** [comment]
Tested on Chrome with Bootstrap 3.3.7 and jQuery 1.12.4.
No problem here!
