### ISSUE TITLE
Maybe wrong title if tooltip attached?

### ISSUE THREAD

**Issue by JayChandler** [tavicu/bs-confirmation#27]
If the elements that triggers the confirmation has a tooltip attached the title from the javascript options will be ignored. There is no way to set a manual title. So this is a little workaround. Maybe it makes sense!

<pre>
Confirmation.prototype.getTitle = function() {
     var a, b = this.$element, c = this.options;
     
     if(!b.attr("data-toggle") == "tooltip"){
       return a = b.attr("data-original-title") || ("function" == typeof c.title ? c.title.call(b[0]) : c.title)
     }
     else{
       return a = ("function" == typeof c.title ? c.title.call(b[0]) : c.title)
     }
  }
</pre>

**Comment by tavicu** [comment]
Hi. Just released a new version.
Now you can set the title in multiple ways.

data-confirmation-title, data-title or title.

This is the priority and if you set data-confirmation-title it will ignore data-title or title so you can use the tooltip and confirmation on the same element.
