### ISSUE TITLE
url not working '#'

### ISSUE THREAD

**Issue by thapliyalmanoj** [tavicu/bs-confirmation#31]
If url not working like my case 

<a href="index.php?get=5" class="btn confirmation">Confirmation</a>
$('.confirmation').confirmation();

just edit your bootstrap-confirmation.js  and override this code on line 128 - 142 .

//  code

$btnOk.addClass(this.getBtnOkClass())
            .html(this.getBtnOkLabel())
            .prepend($('<i></i>').addClass(this.getBtnOkIcon()), " ")
            .attr('href', (that.$element.attr('href')) )
            .attr('target', this.getTarget())
            .off('click').on('click', function(event) {
                options.onConfirm(event, that.$element);
                // If the button is a submit one
                if (that.$element.attr('type') == 'submit')
                    that.$element.closest('form:first').submit();
                that.hide();
                that.inState.click = false;
            });

**Comment by olikhvar** [comment]
Hi
Having problem using this script. the url is not working.
my link is <a href="http://www.google.com" class="btn btn-default" data-toggle="confirmation">Click me</a>

and the output is

http://www.foo.com/demo.html#

I do not know, where i have to modify the code....?

**Comment by mnjthapliyal** [comment]
replace your  bootstrap-confirmation.js  file with this file <a href=" https://www.dropbox.com/s/43t29uo6ed7u86q/bootstrap-confirmation.js?dl=0">LINK</a>

**Comment by olikhvar** [comment]
same result. problem not solved

**Comment by mnjthapliyal** [comment]
OK I HAVE EXAMPLE FILES THIS WILL WORKING 100%.
"https://www.dropbox.com/s/u04nt6ces9eqnc8/testproject.rar?dl=0"

**Comment by mnjthapliyal** [comment]
U Can Find Complete Example Here "https://www.dropbox.com/s/17uwv9wqx38hz55/two.rar?dl=0"

**Comment by olikhvar** [comment]
Thanks a lot, the problem is almost solved. if i want to use more than one link, for example one for google and another link for hotmail or something, what i have to do (you are using id="delete")?

**Comment by tavicu** [comment]
Hi. Just released a new version.

You can now define the url with href or data-href. Until now it was only possible with data-href.
