### ISSUE TITLE
The enable and disable command does not works correctly.

### ISSUE THREAD

**Issue by edwardmeng** [tavicu/bs-confirmation#44]
There is an button in the page like this
`<input type="submit" id="btnOK" class="btn btn-primary" data-toggle="confirmation" data-title="Are you sure to do this?" value="OK">`
and in the global script file, we will register it with bs-confirmation automatically with the following code
`$(function(){
    $('[data-toggle="confirmation"]').confirmation();
})`
In the specified page, I want to disable the confirmation programmatically with the following code
`$('#btnOK').confirmation('disable')`
But after that the btnOK cannot be submitted correctly, especially in the Asp.Net WebForms.

**Comment by tavicu** [comment]
disable function is from the Bootstrap Tooltip and it's not removing the action when click on the button. It will only disable it. Try to use destroy instead of disable.
