### ISSUE TITLE
onHide not passing an element through

### ISSUE THREAD

**Issue by jrseliga** [tavicu/bs-confirmation#45]
onHide does not passthrough the same type of element as onCancel or onConfirm

When executing this in the onConfirm option
`
console.log(element);
`

This is returned:
`
Object[button.btn.btn-default.open]
`

However when executing that same code in the onHide option this is returned:
`
<button class="btn btn-default open" data-original-title="" title="" aria-describedby="confirmation789282">
`

**Comment by tavicu** [comment]
Hi. Just released a new version that resolve this.
