### ISSUE TITLE
Form-data on submit-button is discarded

### ISSUE THREAD

**Issue by addiks** [tavicu/bs-confirmation#47]
When using the confirmation on a submit-button that holds form-data, the form data does not get sent to the server.

Example:

```
<form action="#" method="post">
  <input type="text" name="some_data" value="some_value" />
  <input type="hidden" name="foo" value="bar" />

  <button type="submit" name="action" value="do_something">Do something</button>
  <button type="submit" name="action" value="delete" data-toggle="confirmation">Delete this</button>
</form>
```

When pressing the button "Do something", the post-data submitted to the server is "some_data=some_value&foo=bar&action=do_something".
When pressing the button "Delete this" and press the "Ok" button in the confirmation popup, only "some_data=some_value&foo=bar" get submitted. The "action" on the button is unexpectedly discarded. The plugin should not discard data on the submit-button.

**Comment by tavicu** [comment]
I'm sorry but this is how jQuery submit works.

Changing this will also affect users that don't want this behaviour.

You can insert this "hack" into onConfirm callback.
