### ISSUE TITLE
HTML5 Form Validation

### ISSUE THREAD

**Issue by gathilas** [tavicu/bs-confirmation#49]
Using form.submit() through javascript skips HTML5 form validation.

I made a simple fix but I'm not sure how it affects other use cases. I changed the confirm a tag in the pop over into a button tag with no type attr. That makes the confirm button in the pop over act as a submit button for the form. Then I removed the form.submit() from the js code and let HTML naturally submit the form.

**Comment by HarveyEV** [comment]
Im trying to intercept thew submit and post via ajax. Maybe this is a related issue? Did you sunbit a pull request so we can see what you did?

**Comment by gathilas** [comment]
Truthfully I'm kind of new to this git thing (yeah I'm out of touch) so I'm not sure how or what to do. It doesn't seem to let me create a pull request.

If I remember correctly, in bootstrap-confirmation.js on line 103, I replaced it with this:

`+ '<button data-apply="confirmation">Yes</button>'`

Then I removed line 137-138.

**Comment by tavicu** [comment]
Hi. I have made some changes and now if the form has HTML5 validation and it's not valid it will not be submitted.

Unfortunately it will not show the errors. For that you need to make a "hack".

First you need to create a hidden submit button. Then you need a callback on the onConfirm and if the form it's not valid you need to click the hidden submit button.

You can read more here: https://stackoverflow.com/questions/11381369/html5-required-and-jquery-submit/11382321
