### ISSUE TITLE
Popover is not deleted from DOM when hidden

### ISSUE THREAD

**Issue by potthast** [tavicu/bs-confirmation#5]
When clicking "Cancel" in a confirmation popover, or when clicking outside, it is made invisible but the DOM elements are not removed. Therefore, the popover may be on top of other buttons, e.g., in a menu bar, making them unusable.

A simple fix might be as follows; add the following line after line 31:
<code>$(this).siblings(".popover").remove();</code>

**Comment by tavicu** [comment]
Hey! You must have done some changes because the script as it is is removing the popover from DOM. I just downloaded the version from here and tested.

The "hide" method is made by bootstrap popover, not by my javascript. And is removing the popover from DOM after the fadeOut.
