### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by skitterm** [tavicu/bs-confirmation#53]
Hi. I'd like to use this project, but there seem to be a couple things with the licensing that I'm not sure about. 

1) I noticed on the README that the project is licensed MIT, but I don't see any license notice or text in the javascript files.
2) Where this is a fork of https://github.com/ethaizone/Bootstrap-Confirmation, and that project is listed as being Apache 2.0, does there need to be some mention of what parts are under MIT and what are under Apache 2.0?

I'm no licensing pro, but I had questions about both of these that prevent me from using this library for now (for a commercial project).

**Comment by tavicu** [comment]
Hi. You can use the plugin without a problem in a commercial project :)

**Comment by skitterm** [comment]
Thanks, @tavicu. Unfortunately, for me to use it commercially, I'd need the license notices listed in the distributed code, as I mentioned above. Otherwise I doubt my (or other companies') legal departments would give a green light to use the project.
