### ISSUE TITLE
Applying custom options doesn't work

### ISSUE THREAD

**Issue by Illuminerdy** [tavicu/bs-confirmation#54]
When debugging, this.options has properties like

btnokclass, but the javascript code is looking for btnOkClass.

Chrome converts all HTML attributes to lower case.

**Comment by Illuminerdy** [comment]
Found this:

All attribute names on HTML elements in HTML documents get ASCII-lowercased automatically, so the restriction on ASCII uppercase letters doesn't affect such documents.

**Comment by tavicu** [comment]
Hi. I don't get what is the problem and why you can't debug the code :)

**Comment by Illuminerdy** [comment]
I did debug the code, and fixed it myself.

The confirmation plugin is supposed to allow you to specify options on the element like data-btnOkClass="Confirm", but Chrome will convert it to btnokclass. The plugin only looks for 'btnOkClass'.

So i made the below code convert it and pass it in as options.

         //dropdown confirmations
            $('[data-toggle="tigo-confirmation"]').each(function (el) {
                var options = $(this).data();
                if(options.btnokclass != undefined)
                {
                    options.btnOkClass = options.btnokclass;
                }
                if(options.btnoklabel != undefined)
                {
                    options.btnOkLabel = options.btnoklabel;
                }

                $(this).confirmation(options);
            });

**Comment by tavicu** [comment]
btnOkClass converts to data-btn-ok-class :)

So your code should look like  <a data-btn-ok-class="ok-class"></a>

**Comment by tavicu** [comment]
I've also updated the README with the correct info.

**Comment by Illuminerdy** [comment]
Thanks, didn't know that.
