### ISSUE TITLE
Not working wit ajax loaded content

### ISSUE THREAD

**Issue by mk3d** [tavicu/bs-confirmation#7]
The "click" event was not reconize when content was loaded with ajax

**Comment by tavicu** [comment]
Since this plugin works on Bootstrap Popovers you need to reinitialise the popovers again when you load the content via ajax.

If you want to do this you need to make a function to initialise the script and run it every time after you replaced the content with ajax.

**Comment by xibman** [comment]
Now you can use delegation with popover with attribute selectorlike this: https://github.com/mistic100/Bootstrap-Confirmation

Your work is better because you can prevent default on confirm action
